before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0
  main: ./cmd
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

archives:
- format_overrides:
    - goos: windows
      format: zip

release:
  github:
  prerelease: auto

brews:
- name: templatizer
  homepage: https://github.com/wesovilabs/homebrew-tools
  tap:
    owner: wesovilabs
    name: homebrew-tools
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
