before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  main: ./cmd/templatizer
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
dockers:
  - image_templates:
    - "docker.pkg.github.com/wesovilabs/templatizer/{{.ProjectName}}:latest"
    - "docker.pkg.github.com/wesovilabs/templatizer/{{.ProjectName}}:{{ .Major }}"
    - "docker.pkg.github.com/wesovilabs/templatizer/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
    - "docker.pkg.github.com/wesovilabs/templatizer/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainer.image.created={{.Date}}"
    - "--label=org.opencontainer.image.name={{.ProjectName}}"
    - "--label=org.opencontainer.image.revision={{.FullCommit}}"
    - "--label=org.opencontainer.image.version={{.Version}}"
    - "--label=org.opencontainer.image.source={{.GitURL}}"
