before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0
  main: ./cmd
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

archives:
- format_overrides:
    - goos: windows
      format: zip

release:
  github:
  prerelease: auto

dockers:
  - image_templates:
    - "wesovilabs/templatizer:latest"
    - "wesovilabs/templatizer:{{ .Major }}"
    - "wesovilabs/templatizer:{{ .Major }}.{{ .Minor }}"
    - "wesovilabs/templatizer:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    dockerfile: ./Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--platform=linux/arm64"
brews:
  -
    name: templatizer
    tap:
      owner: wesovilabs
      name: hoebrew-tools
    folder: Formula
    commit_author:
      name: ivancorrales
      email: ivan.corrales.solera@gmail.com
    homepage: https://github.com/wesovilabs/templatizer
    description: "Software to create dynamically projects from templates."
    license: "GN v3"
    dependencies:
      - name: git
      - name: zsh
        type: optional
