name: Development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  buildFrontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cmd/client/templatizer-ui
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: templatizer-ui-build
          path: cmd/client/templatizer-ui/build

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2

  tests:
    runs-on: ubuntu-latest
    needs:
      - buildFrontend
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-build-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/download-artifact@v2
        with:
          name: templatizer-ui-build
          path: cmd/client/templatizer-ui/build

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Clean repository
        run: make clean install

      - name: Run unit tests
        run: make test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.*

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # , macos-10.15, windows-2019 ]
    runs-on: ${{ matrix.os }}
    needs:
      - linters
      - tests
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: templatizer-ui-build
          path: cmd/client/templatizer-ui/build

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Release test
        run: make clean mod-tidy install build

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
