name: Release

on:
  push:
    tags:
      - 'v*'
jobs:

  buildFrontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cmd/client/templatizer-ui
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: templatizer-ui-build
          path: cmd/client/templatizer-ui/build

  goreleaser:
    runs-on: ubuntu-20.04
    needs:
      - buildFrontend
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: templatizer-ui-build
          path: cmd/client/templatizer-ui/build
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install Go project
        run: make install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
